---
sidebar: sidebar
permalink: clean-restore-task.html
keywords: clean room, clean restore, isolated restore, secure recovery, restore
summary: Ransomware Resilience enables you to perform a controlled restoration of files in a clean room. 
---
= Restore files safely with clean restore in NetApp Ransomware Resilience
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Ransomware Resilience enables you to perform a thorough cleaning of your workloads before performing a restore. 

Using the clean room scrubs all files after a ransomware incident to remove infected files. 

The clean restore process is split into seven steps: Setup, analysis, plan, cleaning, recovery, conclusion


== Considerations

// * Number of clean rooms per 


== Create a clean room 

[IMPORTANT]
Clean room is currently in **private preview**. To enroll in the private preview, navigate to the **Recovery** dashboard in Ransowmare Resilience. In the Clean Restore card, select **Sign up** to request access. 

. In Ransomware Resilience, select **Settings**. 
. In the Clean rooms card, select **Add**. 
. Provide the follow inputs: 
    * A **Name** for the clean room. 
    * Provider is pre-determined. 
    * Permissions 
// need info
    * Provide the authentication credentials for your clean restore environment, including **Access key** and **Secret key**. 

. Select **Add** to create the clean room. 
+
You can track the progress in the **Settings** tab. Once the room is created, you can select **Manage**. 

== Perform a clean restore 

. In the **Recovery** section, select the workload you want to restore. Select **Restore**. 
. In the Restore Type options, select **Clean restore** then **Next**. 
.. If you haven't created a clean room for this system, provide the necessary information to link:#create-a-clean-room[create the clean room]. Select **Next**. 
.. If you have created a clean room, select the clean room to use for the restore. 
. Select **Restore**. 
// The clean room is automatically selected if one is already connected to the Console agent. Otherwise, you can select a clean room
// Setup step: 
. After the setup completes, select **Run analysis**. With the analysis, Ransomware Resilience investigates all restore points--snapshots and backups--from the seven days prior to the incident. Ransomware Resilience analyzes the restore points, noting which ones are potentially impacted.
+
Once a restore point is discovered without impacted files, all earlier restore points are skipped. For example, if the ransomware event occured on October 10, and a restore point was discovered on October 7 at 10:21 AM with no impacted files, all restore points prior to October 7 at 10:21 AM are skipped. 

// image

. After the analysis completes, plan your recovery. Ransomware Resilience presents two options: **Least data loss** and **Latest unimpacted restore point**. 
// Synthesizes different restore points to create a restore with the least data loss.
. To view granular file event data, select that files to analyze its encryption status; when it was created, modified, or deleted, and what restore point corresponds to what action. 
. Select **Next** to proceed to cleaning. 
. Track the file cleaning progress. 
.. If cleaning of any file fails, those files are excluded from the recovery. Select if you want to quarantine those files by  saving them to another location. 
// choose location
. Choose where to save the original workload: the original location or an alternate. 
.. If you choose the original location, select whether you want to save a new copy or replace the existing.
.. If you select an alternative location, select the **System** and **Storage VM** then enter the **Path for the new volume** and the **New volume name**. 
. Select **Start recovery** to initiate the recovery. 
. **Release resources and end**. 
. To confirm you want to release the resource, select **End**. 