settings:
  name: NetApp Ransomware Resilience
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  release_notes_autogen:
    release_notes_repo: console-relnotes
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: NetApp Ransomware Resilience docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new in Ransomware Resilience
          url: /whats-new.html
        - title: Known limitations
          url: /rp-reference-limitations.html
    - title: Get started
      entries:
        - title: Learn about Ransomware Resilience
          url: /concept-ransomware-resilience.html
        - title: Prerequisites
          url: /rp-start-prerequisites.html
        - title: Quick start
          url: /rp-start-quick-start.html
        - title: Set up Ransomware Resilience 
          url: /rp-start-setup.html
        - title: Set up licensing
          url: /rp-start-licenses.html
        - title: Discover workloads
          url: /rp-start-discover.html 
    - title: Use Ransomware Resilience 
      entries: 
        - title: Access Ransomware Resilience
          url: /rp-start-login.html
        - title: Configure backup destinations
          url: /task-backup-destination.html
        - title: View workload health using the Dashboard
          url: /rp-use-dashboard.html
    - title: Detect and protect
      entries: 
        - title: Review protection 
          url: /task-review-protection.html
        - title: Protect workloads
          url: /rp-use-protect.html
        - title: Configure user activity detection
          entries: 
          - title: Learn about user activity detection 
            url: /concept-user-behavior.html
          - title: User activity requirements 
            url: /reference-user-activity-requirements.html
          - title: Configure agents and collectors
            url: /suspicious-user-activity.html
        - title: Manage protection groups 
          url: /task-protection-group.html
        - title: Scan for personally identifiable data
          url: /task-classify.html 
        - title: Conduct a readiness drill
          url: /rp-start-simulate.html  
        - title: Configure SIEM 
          url: /task-siem.html       
    - title: Respond and recover
      entries:
        - title: Respond to a detected alert 
          url: /rp-use-alert.html
        - title: Recover from a ransomware attack
          url: /rp-use-recover.html
        - title: Download reports
          url: /rp-use-reports.html 
    - section: support
    - title: FAQ
      url: /rp-start-faq.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: NetApp Data Services
  repo: data-services-family
