---
sidebar: sidebar
permalink: reference-user-activity-sizing.html
keywords: data breach, user activity, suspicious user activity, machine sizing, cores, events per seconds, ram
summary: Before creating a user activity agent, run a script to understand the sizing requirements for your workloads and machine. 
---
= Assess sizing requirements for suspicious user activity in NetApp Ransomware Resilience
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
Before creating a user activity agent, run a script to understand the sizing requirements for your workloads and machine. 

== Find your event rate 

* Cluster IP address
* Cluster admin username and password
* You must have `sshpass` installed on the Linux machine (you can install with the command `yum install sshpass` or download from the internet)

NetApp provides a script 

Once you've installed the agent, run the `server_data_rate_checker.sh` script as an admin:
`/opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh`

When prompted, provide the cluter IP address, the admin username, and the admin password. 

The script takes approximately five minutes to run. When it completes, the command line displays the event rate, for example "Svm svm_rate is generating 100 events/sec."
+
Use the event rate to calculate your sizing.

By default, the script runs for a maximum of five storage VMs. If your environment includes more than 5 SVMs, you can modify the script accordingly. Regardless of the number of SVMs, the script takes approximately five minutes to get an average event rate reading. 
