---
sidebar: sidebar
permalink: reference-soar.html
keywords: ransomware protection, soar, security orchestration, microsoft sentinel, splunk, automation, threat response, playbook
summary: Integrate and use SOAR playbooks to automate NetApp Ransomware Resilience threat response tasks.
---
= Integrate a SOAR playbook for NetApp Ransomware Resilience
:icons: font
:imagesdir: ./media/

[.lead]
Ransomware Resilience offers security orchestration, automation, and response (SOAR) playbooks that enable you to automate tasks such as threat response. 

Ransomware Resilience playbooks offer the following capabilities:

* Create a snapshot of a volume
* Enrich an IP address with threat intelligence
* Enrich storage information for a given agent and system
* Take a volume offline for incident response
* Test connectivity
* Review the status of an enrichment job

== Supported playbooks

Ransomware Resilience offers playbooks for Microsoft Sentinel and Splunk. Review the respective GitHub pages for setup details. 

* link:https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/NetApp%20Ransomware%20Resilience/Playbooks[Microsoft Sentinel^]
* link:https://github.com/splunk-soar-connectors/netappransomwareresilienceSplunk[Splunk^]

[NOTE]
For Splunk cloud, you must be running platform version 7.0, 7.1, 7.2, 8.0, or 8.4. For more information, see link:https://splunkbase.splunk.com/app/8483[Splunkbase^].

== More information

* link:task-siem.html[Connect NetApp Ransomware Resilience to a SIEM for threat analysis and detection]