---
sidebar: sidebar
permalink: reference-soar.html
keywords: ransomware protection, soar, security orchestration, microsoft sentinel, splunk, automation, threat response, playbook
summary: Integrate and use SOAR playbooks to automate NetApp Ransomware Resilience threat response tasks.
---
= Integrate a SOAR playbook for NetApp Ransomware Resilience
:icons: font
:imagesdir: ./media/

[.lead]
Ransomware Resilience offers security orchestration, automation, and response (SOAR) playbooks that enable you to automate tasks such as threat response. 

== Supported playbooks

Ransomware Resilience supports the following playbooks. For setup and playbook details, select the link in the table. 

[cols=3,options="header",cols="20,35,45",width="100%"]
|===
| Service | Details | Capabilities
| link:https://github.com/splunk-soar-connectors/netappransomwareresilience[Splunk^] 
a|
* Cloud & on-premises support
* For cloud, you must be running platform version 7.0, 7.1, 7.2, 8.0, or 8.4.
a|
* Test connectivity
* Enrich an IP address with threat intelligence
* Enrich storage information for a given agent and system
* Create a snapshot of a volume
* Take a volume offline for incident response
* Check the status of an enrichment job
|===

== More information

* link:task-siem.html[Connect NetApp Ransomware Resilience to a SIEM for threat analysis and detection]