---
sidebar: sidebar
permalink: rp-reference-roles.html
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account
summary: NetApp Ransomware Resilience employs roles to govern the access that each user has to specific features and actions. 

---

= NetApp Ransomware Resilience role-based access
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
NetApp Ransomware Resilience employs roles to govern the access that each user has to specific features and actions. 

Ransomware Resilience uses the following roles that are specific to Ransomware Resilience. 

* *Ransomware Resilience admin*: Manage actions on the Protect, Alerts, Recover, Settings, and Reports tabs.
* *Ransomware Resilience viewer*: View NetApp workload data, view alert data, download recovery data, and download reports.
* *Ransomware resilience user behavior admin*: Create and manage user behavior detection settings.
* *Ransomware resilience user behavior viewer*: View user behavior detection results. 

These roles are in addition to the Console platform roles that govern access to the Console service and other services, such as data protection, workload management, and so on. For details about all Console platform roles, see https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html[the setup and administration documentation^].

The following table indicates the actions that each Ransomware Resilience role can perform. 

[cols=3*,options="header",cols="40,20a,20a",width="100%"]
|===
| Feature and action
| Ransomware Resilience admin
| Ransomware Resilience viewer

| View dashboard and all tabs | Yes | Yes
| On dashboard, update recommendation status | Yes | No
| Start free trial | Yes | No 
| Initiate discovery of workloads | Yes | No
| Initiate rediscovery of workloads | Yes | No

3+| *On the Protect tab*: 
| Add, modify, or delete protection plans | Yes | No
| Protect workloads | Yes | No
| Identify exposure to sensitive data| Yes | No 
| List protection plans and details | Yes | Yes
| List protection groups    | Yes | Yes
| View protection group details | Yes | Yes
| Create, edit or delete protection group | Yes | No 
| Download data| Yes | Yes 
3+| *On the Alerts tab*: 
| View alerts and alert details | Yes | Yes 
| Edit incident status | Yes | No
| Mark alert for recovery | Yes | No
| View incident details | Yes | Yes
| Dismiss or resolve incicents | Yes | No
| Block user | Yes | No
| Get full list of impacted files| Yes | No 
| Download alerts data | Yes | Yes 
3+| *On the Recover tab*: 
| Download impacted files| Yes | No 
| Restore workload | Yes | No 
| Download recovery data | Yes | Yes
| Download reports | Yes | Yes
3+| *On the Settings tab*:
| Add or modify backup destinations| Yes | No 
| List backup destinations| Yes | Yes
| View connected SIEM targets | Yes | Yes
| Add or modify SIEM targets | Yes | No
| Connect workload security targets | Yes | No
| View workload security connection status  | Yes | Yes
| Disconnect workload security targets | Yes | No
| Configure readiness drill | Yes | No
| Start readiness drill | Yes | No
| Reset readiness drill | Yes | No
| Edit readiness drill  | Yes | No
| Review readiness drill status | Yes | Yes
| Update discovery configuration | Yes | No
| View discovery configuration | Yes | Yes

3+| *On the Reports tab*:
| Download reports | Yes | Yes

|===
