---
sidebar: sidebar
permalink: rp-reference-limitations.html
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account
summary: Known limitations identify platforms, devices, or functions that are not supported by this release of the product.

---

= Known limitations of NetApp Ransomware Resilience
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

== Readiness drill Reset option issue


If you select an ONTAP 9.11.1 volume for the ransomware attack readiness drill, Ransomware Resilience sends an alert. If you recover the data using the "clone-to-volume" option and reset the drill, the reset operation fails.

== Amazon FSx for NetApp ONTAP limitations

The Amazon FSx for NetApp ONTAP system is supported in Ransomware Resilience. The following limitations apply to Amazon FSx for ONTAP:

* Backup policies are not supported for Amazon FSx for ONTAP. In this environment, you should perform backup operations using the Amazon FSx for backups. You can restore these workloads using Ransomware Resilience. 
* Restore operations are performed from snapshots only.

