---
sidebar: sidebar
permalink: rp-start-prerequisites.html
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites
summary: Get started with BlueXP ransomware protection by verifying support for your environment, network access, login and web browser.
---

= BlueXP ransomware protection prerequisites
:hardbreaks:
:icons: font
:imagesdir: ./media/get-started/

[.lead]
Get started with BlueXP ransomware protection by verifying the readiness of your operational environment, login, network access, and web browser.

To use BlueXP ransomware protection, you'll need these prerequisites: 

* For the preview version, you’ll need an account in NetApp StorageGRID and AWS S3 for backup targets and the AWS permissions set.
+
Refer to the https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html[AWS permissions list^] for details. 

* ONTAP 9.11.1 and later
** Cluster admin ONTAP permissions
** A license for NetApp Autonomous Ransomware Protection, used by BlueXP ransomware protection, on the ONTAP instance, depending on the version of ONTAP you are using. Refer to https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html[Autonomous Ransomware Protection overview^].


* In BlueXP: 

** A BlueXP Connector per region in the cloud or on an on-premise region must be set up in NetApp BlueXP. All source and working environments must be on the same BlueXP account. Refer to https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[BlueXP documentation to configure the Connector^].
+
NOTE: If you have multiple BlueXP Connectors, the service will scan data across all Connectors beyond the one that currently shows in the BlueXP UI. 

** The BlueXP backup and recovery service with backup enabled on the working environment
** The BlueXP working environment with NetApp NAS on-premises storage should be set up. 
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html[Standard BlueXP requirements^]


