---
sidebar: sidebar
permalink: rp-start-faq.html
keywords: ransomware protection faq, ransomware protection frequently asked questions
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for BlueXP ransomware protection
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.

== Access

*What's the BlueXP ransomware protection URL?*
For the URL, in a browser, enter: https://console.bluexp.netapp.com/[https://console.bluexp.netapp.com/^] to access the BlueXP console. 

*Do you need a license to use BlueXP ransomware protection?*

You can use the following license types:

* Sign up for a 90-day free trial.
* Purchase a pay-as-you-go (PAYGO) subscription with Amazon Web Services (AWS) Marketplace.
* Bring your own license (BYOL), which is a NetApp License File (NLF) that you obtain from your NetApp Sales Rep. You can use the license serial number to get the BYOL activated in BlueXP digital wallet.


*How do you enable BlueXP ransomware protection?* 
BlueXP ransomware protection does not require any enablement. The ransomware protection option is automatically enabled on the BlueXP left navigation. 

To get going, you need to sign up or reach out to your NetApp Sales rep to try out this service. Then, when you use the BlueXP Connector, it will include the appropriate capabilities for the service.


**Does BlueXP ransomware protection available in standard, restricted, and private modes?**
At this time, BlueXP ransomware protection is available only in standard mode. Stay tuned for more. 

For an explanation about these modes across all BlueXP services, refer to https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html[BlueXP deployment modes^].

**How are access permissions handled?**
Only account admins have the ability to initiate the service and discover workloads (because this involves committing to usage of a resource). Subsequent interactions can be done by any role.

**What device resolution is best?**
The recommended device resolution for BlueXP ransomware protection is 1920x1080 or better. 

**Which browser should I use?**
Any modern browser will work. 



== Interaction with other services

*Is BlueXP ransomware protection aware of protection settings made in NetApp ONTAP?*
Yes, BlueXP ransomware protection discovers Snapshot schedules set in ONTAP. 

*If you set a policy using BlueXP ransomware protection, do you have to make future changes only in this service?* 
We recommend that you make policy changes from the BlueXP ransomware protection service.

== Workloads

**What makes up a workload?**
A workload includes all volumes that are used by a single application instance. For example, an Oracle DB instance deployed on ora3.host.com can have vol1 and vol2 for its data and logs, respectively. Those volumes together constitute the workload for that specific instance of the Oracle DB instance.

*How does BlueXP ransomware protection prioritize workload data?*
Data priority is determined by the Snapshot copies made and backups that are scheduled. 

The workload priority is determined by the following Snapshot frequencies: 

* *Critical*: Snapshot copies taken less than 1 per hour (highly aggressive protection schedule)
* *Important*: Snapshot copies taken less than 1 per day but greater than 1 per hour
* *Standard*: Snapshot copies taken more than 1 per day 

**New volume added, but doesn't appear yet**
If you added a new volume to your environment, initiate discovery again and apply protection policies to protect that new volume. 

**The Dashboard doesn't show all my workloads. What might be wrong?**
Currently, only NFS and CIFS volumes are supported. iSCSI volumes  and other non-supported configurations are filtered out and do not appear on the Dashboard. 

== Protection policies

*Do BlueXP ransomware policies co-exist with the other kinds of workload policies?*
At this time, BlueXP backup and recovery (Cloud Backup) supports one backup policy per volume. So, BlueXP backup and recovery and BlueXP ransomware protection share backup policies.

Snapshot copies are not limited and can be added separately from each service.



