---
sidebar: sidebar
permalink: rp-start-prerequisites.html
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites
summary: Get started with BlueXP ransomware protection by verifying support for your environment, network access, login and web browser.
---

= BlueXP ransomware protection prerequisites
:hardbreaks:
:icons: font
:imagesdir: ./media/get-started/

[.lead]
Get started with BlueXP ransomware protection by verifying the readiness of your operational environment, login, network access, and web browser.

To use BlueXP ransomware protection, you'll need the prerequisites. 


== In BlueXP 


* A BlueXP user account with Organization Admin privileges for discovering resources.

* A BlueXP organization with at least one active BlueXP Connector connecting to on-premises ONTAP clusters or to Cloud Volumes ONTAP in AWS or in Azure. 

* The BlueXP Connector must have the `cloudmanager-ransomware-protection` container in an active state. 

* At least one BlueXP working environment with a NetApp on-premises ONTAP cluster or Cloud Volumes ONTAP in AWS or Azure. BlueXP ransomware protection supports both NAS (NFS and SMB) and SAN (iSCSI, FC, and NVMe) protocols. 

** ONTAP or Cloud Volumes ONTAP clusters with ONTAP OS version 9.11.1 or greater are supported. 
[NOTE]
SAN workloads are supported only in ONTAP 9.17.1 and later. 

** If your on-premises ONTAP clusters or Cloud Volumes ONTAP in AWS or in Azure cloud are not already onboarded in BlueXP, you need a BlueXP Connector. 
+
Refer to https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html[Learn how to configure a BlueXP Connector] and https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html[standard BlueXP requirements^].
+
NOTE: If you have multiple BlueXP Connectors in a single BlueXP organization, the BlueXP ransomware protection service will scan ONTAP resources across all Connectors beyond the one that is currently selected in the BlueXP UI. 

//All source and working environments must be in the same BlueXP organization. 


//** A BlueXP Connector per each Virtual Private Cloud (VPC) or on an on-premises region must be set up in BlueXP. Refer to https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[BlueXP documentation to configure the Connector^].

== In ONTAP 9.11.1 and later

* An ONTAP One license is enabled on the on-premises ONTAP instance.


* A license for NetApp Autonomous Ransomware Protection, used by BlueXP ransomware protection, enabled on the on-premises ONTAP instance, depending on the version of ONTAP you are using. Refer to https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html[Autonomous Ransomware Protection overview^].
+
NOTE: The general release of BlueXP ransomware protection, unlike the Preview release, includes a license for NetApp Autonomous Ransomware Protection technology. Refer to https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html[Autonomous Ransomware Protection overview^] for details.
+
For more licensing details, refer to link:concept-ransomware-protection.html[Learn about BlueXP ransomware protection].

* To apply protection configurations (such as enabling Autonomous Ransomware Protection and others), BlueXP ransomware protection needs admin permissions on the ONTAP cluster. The ONTAP cluster should have been onboarded using ONTAP cluster admin user credentials only. 

* If the ONTAP cluster is already onboarded in BlueXP using non-admin user credentials, then the non-admin user permissions must be updated with necessary permissions by logging into the ONTAP cluster, described on this page. 


== For data backups

* An account in NetApp StorageGRID, AWS S3, or Azure Blob for backup targets and the access permissions set. 
+
Refer to the https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html[AWS, Azure, or S3 permissions list^] for details. 

* The BlueXP backup and recovery service does not need to be enabled on the working environment. 
+
The BlueXP ransomware protection service helps configure a backup destination through the Settings option. See link:rp-use-settings.html[Configure settings].


== Update non-admin user permissions in an ONTAP working environment

If you need to update non-admin user permissions for a particular working environment, complete these steps. 




.  Log in to BlueXP and look for the working environment that needs its ONTAP user permissions updated. 

. Double-click on the working environment to see details. 
. Select *View additional information* to display the username. 
. Log in to the ONTAP cluster CLI using the admin user. 
. Display the existing roles for that user. Enter: 
+
----
security login show -user-or-group-name <username>
----

. Change the role for the user. Enter: 
+
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----

. Return to the BlueXP ransomware protection UI to use it. 