---
sidebar: sidebar
permalink: rp-start-prerequisites.html
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites
summary: Get started with BlueXP ransomware protection by verifying support for your environment, network access, login and web browser.
---

= BlueXP ransomware protection prerequisites
:hardbreaks:
:icons: font
:imagesdir: ./media/get-started/

[.lead]
Get started with BlueXP ransomware protection by verifying the readiness of your operational environment, login, network access, and web browser.

To use BlueXP ransomware protection, you'll need these prerequisites: 

* An account in NetApp StorageGRID or AWS S3 for backup targets and the access permissions set
+
Refer to the https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html[AWS permissions list^] for details. 

* ONTAP 9.11.1 and later
** Cluster admin ONTAP permissions
** A license for NetApp Autonomous Ransomware Protection, used by BlueXP ransomware protection, enabled on the on-premises ONTAP instance, depending on the version of ONTAP you are using. Refer to https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html[Autonomous Ransomware Protection overview^].
+
NOTE: The general release of BlueXP ransomware protection, unlike the Preview release, includes a license for NetApp Autonomous Ransomware Protection technology. Refer to https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html[Autonomous Ransomware Protection overview^] for details.
+
For more licensing details, refer to link:concept-ransomware-protection.html[Learn about BlueXP ransomware protection].


* In BlueXP: 

** A BlueXP working environment with NetApp on-premises storage (using NAS or CIFS protocols)
** A BlueXP Connector per each Virtual Private Cloud (VPC) or on an on-premises region must be set up in BlueXP. Refer to https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[BlueXP documentation to configure the Connector^].
+
NOTE: If you have multiple BlueXP Connectors, the service will scan data across all Connectors beyond the one that currently shows in the BlueXP UI. 



** A BlueXP account with at least one active Connector connecting to on-premises ONTAP clusters. All source and working environments must be on the same BlueXP account. 
** A BlueXP user account with Account Admin privileges for discovering resources
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html[Standard BlueXP requirements^]


NOTE: The BlueXP backup and recovery service does not need to be already enabled on the working environment. The BlueXP ransomware protection service helps configure a backup destination through the Settings option. See link:rp-use-settings.html[Configure settings].