---
sidebar: sidebar
permalink: rp-use-settings.html
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware settings, backup destination
summary: You can configure several options, including a backup destination and threat detection in the settings page.
---
= Configure protection settings in NetApp Ransomware Resilience
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
When you launch NetApp Ransomware Resilience for the first time, it discovers workloads. If you add or need to rediscover workloads, use the Ransomware Resilience settings dashboard to configure workload discovery. 
include::_include/console-role-admin.adoc[]

//You can also show future Preview features. 

//Enabling threat detection automatically sends data to a security and event management system (SIEM) or extended detection and response (XDR) server for threat analysis and detection. 

== Configure workload discovery 

You can configure workload discovery to automatically discover new workloads in your environment.

. In the Settings page, locate the *Workload discovery* tile.
. In the *Workload discovery* tile, select *Discover workloads*.
+
This page shows Console agents with systems that were not selected earlier, newly available Console agents, and newly available systems. This page doesn't show those systems that were previously selected. 

. Select the Console agent where you want to discover workloads.
. Review the list of systems.
. Check the systems where you want to discover workloads or select the box at the top of the table to discover workloads in all discovered workload environments.
. Do this for other systems as needed.

. Select *Discover* to have Ransomware Resilience automatically discover new workloads in the selected Console agent.

[TIP]
From the Workload discovery card in Settings, select the action menu `...` then **Download report (JSON)** to review a list of supported and unsupported workloads in your systems. 

