---
sidebar: sidebar
permalink: rp-use-recover.html
keywords: ransomware protection recovery, recover from a ransomware attack, recovery point, RPA
summary: After an attack, BlueXP ransomware protection verifies that the backup data on secondary storage is clean, recommends a recovery point actual (RPA), and orchestrates the workflow for a crash-resistant recovery. 
---

= Recover from a ransomware attack (after incidents are neutralized)
:hardbreaks:
:icons: font
:imagesdir: ./media

[.lead]
After an attack, BlueXP ransomware protection verifies that the backup data on secondary storage is clean, recommends a recovery point actual (RPA), and orchestrates the workflow for a crash-resistant recovery. 




=== View workloads that are in a recovery state

Review the workloads that are in one of these recovery statuses: 

* Restore needed
* Queued
* In progress 
* Restored 
* Failed 

.Steps 
. From the BlueXP left navigation, select *Protection* > *Ransomware protection*. 

. Do one of the following: 
+
* From the Dashboard, review the Workload data incidents pane and select *View all*. 
* From the menu, select *Recovery*.


. Review the workload information in the *Recover* page.  

=== Recover a workload 

Using BlueXP ransomware protection, the storage administrator can review the recommended restore point and determine how best to recover workload data. 

You can restore data at different levels: 

* Recover an application at the application level, volume level, and or file level. 
* Recover a file share at the volume level. 
* Recover a datastore at the VM level.

The process differs slightly depending on the workload type. 

.Steps 

. From the BlueXP left navigation, select *Protection* > *Ransomware protection*. 

. From the menu, select *Recovery*.

. Review the workload information in the *Recovery* page.  

. Select a workload that is in the “Restore needed” state. 

. To see the protection details before you recover the workload, select the *Actions* ... icon on the right and select *View protection details*.  

. To restore, select *Restore*.

. *Restore scope*: Select the type of restore you want to complete: 
** Application consistent
** Volume level
** File level: You can specify a folder or single files to restore. 
+
TIP: You can select up to 100 files or a single folder. 

. If you selected Volumes or Files, choose the volume that contains the files you want to restore or choose the files. 

. *Source*: Select the down arrow next to Source to see details: 

.. Select the restore point that you want to use to restore the data. 
+
TIP: BlueXP ransomware protection identifies the best restore point as the latest backup just before the incident and shows a “Recommended” indication. 

.. If you chose to restore files, specify a single folder or the files you want to restore.

. *Destination*: Select the down arrow next to Destination to see details.

.. Choose where to restore the data: original source location or an alternate location that you can specify. 
+ 
TIP: While the original files or directory will be overwritten by the restored data, the original file and folder names will remain the same unless you specify new names. 

.. Select the working environment. 
.. Select the Storage VM. 
.. Optionally, enter the path. 
+
TIP: If you don't specify a path for the restore, the files will be restored to a new volume at the top-level directory. 

. Review your selections. 
. Select *Restore*. 

. From the menu, select *Recover* to review the workload on the Recovery page where the status of the operation moves through the states.