---
sidebar: sidebar
permalink: rp-use-recover.html
keywords: ransomware protection recovery, recover from a ransomware attack, recovery point, RPA
summary: After an attack, BlueXP ransomware protection verifies that the backup data on secondary storage is clean, recommends a recovery point actual (RPA), and orchestrates the workflow for a crash-resistant recovery. 
---

= Recover from a ransomware attack (after incidents are neutralized)
:hardbreaks:
:icons: font
:imagesdir: ./media

[.lead]
After workloads have been marked "Ready for recovery", BlueXP ransomware protection recommends a recovery point actual (RPA) and orchestrates the workflow for a crash-resistant recovery. 




== View workloads that are in a recovery state

Review the workloads that are in the "Restore needed" recovery statuses. 



.Steps 
. From the BlueXP left navigation, select *Protection* > *Ransomware protection*. 

. Do one of the following: 
+
* From the Dashboard, review the Workload data incidents pane and select *View all*. 
* From the menu, select *Recovery*.


. Review the workload information in the *Recovery* page.  

== Recover a workload 

Using BlueXP ransomware protection, the security storage administrator can determine how best to recover workloads either from the recommended restore point or their preferred restore point.  

The security storage admin can recover data at different levels: 

* Recover an application at the volume level  or file and folder level. 
* Recover a file share at the volume level, directory, or file/folder level. 
* Recover a datastore at the VM level.

The process differs slightly depending on the workload type. 

.Steps 

. From the BlueXP left navigation, select *Protection* > *Ransomware protection*. 

. From the menu, select *Recovery*.

. Review the workload information in the *Recovery* page.  

. Select a workload that is in the “Restore needed” state. 


. To restore, select *Restore*.

. *Restore scope*: Select the type of restore you want to complete: 

** Volume level
** File level: You can specify a folder or single files to restore. 
+
TIP: You can select up to 100 files or a single folder. 
//** Application consistent

. Continue with one of the following procedures depending on whether you chose application, volume, or file. 

//=== Restore an application workload at the application level

//On the Recovery page, after you select an application to restore, continue with these steps. 

//. *Source*: Select the down arrow next to Source to see details: 

//.. Select the restore point that you want to use to restore the data. 
//+
//TIP: BlueXP ransomware protection identifies the best restore point as the latest backup just before the incident and shows a “Recommended” indication. 

//. *Destination*: Select the down arrow next to Destination to see details.

//.. Select the working environment. 
//.. Select the Storage VM. 
//.. Select the aggregate. 
//.. Review the new volume name. 
//+
//TIP: The new volume name appears as original volume name + backup name + backup date.

//. Select *Next*.
//. Review your selections. 
//. Select *Restore*. 

//. From the top menu, select *Recovery* to review the workload on the Recovery page where the status of the operation moves through the states.

=== Restore an application workload at the volume level

On the Recovery page, after you select an application to restore, continue with these steps. 

. On the Restore page, in the Restore scope, select *By volume*. 

. On the list of volumes, select the volume you want to restore. 

. *Source*: Select the down arrow next to Source to see details: 

.. Select the restore point that you want to use to restore the data. 
+
TIP: BlueXP ransomware protection identifies the best restore point as the latest backup just before the incident and shows a “Recommended” indication. 

. *Destination*: Select the down arrow next to Destination to see details.

.. Select the working environment. 
.. Select the Storage VM. 
.. Select the aggregate. 
.. Review the new volume name. 
+
TIP: The new volume name appears as original volume name + backup name + backup date.

. Select *Next*.
. Review your selections. 
. Select *Restore*. 

. From the top menu, select *Recovery* to review the workload on the Recovery page where the status of the operation moves through the states.

=== Restore an application workload at the file level

On the Recovery page, after you select an application to restore, continue with these steps. 

. On the Restore page, in the Restore scope, select *By file*. 

. On the list of volumes, select the volume you want to restore. 

. *Source*: Select the down arrow next to Source to see details: 

.. Select the restore point that you want to use to restore the data. 
+
TIP: BlueXP ransomware protection identifies the best restore point as the latest backup just before the incident and shows a “Recommended” indication. 

.. Select up to 100 files or a single folder to restore. 

. *Destination*: Select the down arrow next to Destination to see details.

.. Choose where to restore the data: original source location or an alternate location that you can specify. 
+ 
TIP: While the original files or directory will be overwritten by the restored data, the original file and folder names will remain the same unless you specify new names. 

.. Select the working environment. 
.. Select the Storage VM. 
.. Optionally, enter the path. 
+
TIP: If you don't specify a path for the restore, the files will be restored to a new volume at the top-level directory.
.. Select whether you want the names of the restored files or directory to be the same names as the current location or different names. 

. Select *Next*.
. Review your selections. 
. Select *Restore*. 

. From the top menu, select *Recovery* to review the workload on the Recovery page where the status of the operation moves through the states.


=== Restore a file share or datastore at the volume or file level


On the Recovery page, after you selected a file share or datastore to restore, continue with these steps. 

. On the Restore page, in the Restore scope, select *By volume* or *By file*. 

. On the list of volumes, select the volume you want to restore. 

. *Source*: Select the down arrow next to Source to see details: 

.. Select the restore point that you want to use to restore the data. 
+
TIP: BlueXP ransomware protection identifies the best restore point as the latest backup just before the incident and shows a “Recommended” indication. 

. *Destination*: Select the down arrow next to Destination to see details.

.. Choose where to restore the data: original source location or an alternate location that you can specify. 
+ 
TIP: While the original files or directory will be overwritten by the restored data, the original file and folder names will remain the same unless you specify new names. 

.. Select the working environment. 
.. Select the Storage VM. 
.. Optionally, enter the path. 
+
TIP: If you don't specify a path for the restore, the files will be restored to a new volume at the top-level directory.

. Review your selections. 
. Select *Restore*. 

. From the menu, select *Recovery* to review the workload on the Recovery page where the status of the operation moves through the states.



=== Restore a VM file share at the VM level

On the Recovery page after you selected a VM to restore, continue with these steps. 

. *Source*: Select the down arrow next to Source to see details: 

.. Select the restore point that you want to use to restore the data. 
+
TIP: BlueXP ransomware protection identifies the best restore point as the latest backup just before the incident and shows a “Recommended” indication. 


. *Destination*: Select the down arrow next to Destination to see details.

.. Choose where to restore the data: original source location or an alternate location that you can specify. 
+ 
TIP: While the original files or directory will be overwritten by the restored data, the original file and folder names will remain the same unless you specify new names. 

.. Select the working environment. 
.. Select the Storage VM. 
.. Optionally, enter the path. 
+
TIP: If you don't specify a path for the restore, the files will be restored to a new volume at the top-level directory. 

. Review your selections. 
. Select *Restore*. 

. From the menu, select *Recovery* to review the workload on the Recovery page where the status of the operation moves through the states.