---
sidebar: sidebar
permalink: rp-use-settings.html
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware settings, backup destination
summary: You can configure several options, including a backup destination and threat detection in the settings page.
---
= Configure protection settings in NetApp Ransomware Resilience
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
In the NetApp Ransomware Resilience settings tab, you can configure backup destinations, conduct an attack readiness drill, configure workload discovery, or configure suspicious user activity detection.

include::_include/console-role-admin.adoc[]

//You can also show future Preview features. 

//Enabling threat detection automatically sends data to a security and event management system (SIEM) or extended detection and response (XDR) server for threat analysis and detection. 

*What can you do in the Settings page?*
From the Settings page, you can do the following: 

* Simulate a ransomware attack by conducting a readiness drill and respond to a simulated ransomware alert. For details, see link:rp-start-simulate.html[Conduct a ransomware attack readiness drill].

* Configure workload discovery.
* Configure suspicious user activity reporting. For more information, see link:suspicious-user-activity.html[Suspicious user activity].
* Add a backup destination.
* Connect your security and event management system (SIEM) for threat analysis and detection. Enabling threat detection automatically sends data to your SIEM for threat analysis. For more information, see link:task-siem.html[Connect NetApp Ransomware Resilience to a SIEM]. 
//* Show upcoming Technology Preview features.

== Simulate a ransomware attack

Conduct a ransomware readiness drill by simulating a ransomware attack on a newly created, sample workload. Then, investigate the simulated attack and recover the sample workload. This feature helps you know that you are prepared in the event of an actual ransomware attack by testing alert notification, response, and recovery processes. You can run a ransomware readiness drill multiple times. 

For details, refer to link:rp-start-simulate.html[Conduct a ransomware attack readiness drill].

== Configure workload discovery 

You can configure workload discovery to automatically discover new workloads in your environment.

. In the Settings page, locate the *Workload discovery* tile.
. In the *Workload discovery* tile, select *Discover workloads*.
+
This page shows Console agents with systems that were not selected earlier, newly available Console agents, and newly available systems. This page doesn't show those systems that were previously selected. 

. Select the Console agent where you want to discover workloads.
. Review the list of systems.
. Check the systems where you want to discover workloads or select the box at the top of the table to discover workloads in all discovered workload environments.
. Do this for other systems as needed.

. Select *Discover* to have Ransomware Resilience automatically discover new workloads in the selected Console agent.

[TIP]
From the Workload discovery card in Settings, select the action menu `...` then **Download report (JSON)** to review a list of supported and unsupported workloads in your systems. 

