---
sidebar: sidebar
permalink: task-exclude-files.html
keywords: ransomware resilience, user behavior, exclude files, 
summary: After an attack, NetApp Ransomware Resilience verifies that the backup data on secondary storage is clean, recommends a recovery point actual (RPA), and orchestrates the workflow for a crash-resistant recovery. 
---
= Manage user activity detection alerts and files in Ransomware Resilience
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
After you configure user activity detection in NetApp Ransomware Resilience, you can modify the list of users or file paths to exclude them from alerts or monitoring. 

You must have configured user behavior monitoring before you can perform this task. 

== Exclude file paths from monitoring 

Each file path must begin with a volume name. It can include up to three sub-directories for that volume, for example "volume/directory/subdirectory/subdirectory2". You can exclude file paths by enterring them manually or uploading a CSV file that lists the paths. 

.Steps
. In Ransomware Resilience, select **Settings**. 
. In the User activity monitoring card, select **Manage**. 
. Select hte *Excluded from monitoring* tab. 
. Select **Add** to enter the file paths for exclusion. 
. To enter the file paths in the UI, select the *Enter manually* radio button then enter the file path, for example "volume/directory/subdirectory/". To enter additional file paths, select **Select file path".
+
. To upload a list of file paths, select the **Upload** radio button. Select the upload button to choose the CSV file.
. Select **Add**. 

.Result
When the operation completes successfully, Ransomware Resilience begins excluding files in the noted paths from monitoring for suspicious user behavior. You can review the list of paths at any time from the Settings menu. If you need to enable monitoring for the file paths again, you can remove them from the list. 

=== Exclude users from alerts

If there are certain trusted users whose behavior might trigger user behavior alerts, you can exclude them from alerts. 

.Steps
. In Ransomware Resilience, select **Settings**. 
. In the Settings dashboard, locate the User activity card then select **Manage**. 
. Select the **Exclude from monitoring** tab. 
. To review individual users in the UI, choose **Select manually**. To upload a list of excluded users, select **Upload**. 
.. If you selected **Select manually**, select the checkbox next to the names of the specific users you want to exclude. 
.. If you select **Upload**, download the CSV or JSON file that includes the list of all the users. Select **Download** to access the list. 
+
On your local machine, review the file. Remove the names of all users that you want to maintain detection for. When the list includes only the names of users you want to exclude from detection, save it.
+
In Ransomware Resilience, select **Upload**. Locate and upload the file. 
. Select **Add** to complete adding the users to the exlcusion list. 
. In the **Excluded users** tab, the names of the users removed from user behavior detection alerts now display in the dashboard. 

[TIP]
You can also exclude a user directly from an alert. For more information, see link:rp-use-alert.html[Respond to ransomware alerts].
