---
sidebar: sidebar
permalink: task-siem.html
keywords: ransomware protection, SIEM, security event management system, soar, playbook, orchestration, event management
summary: You can automatically send data from NetApp Ransomware Resilience to your security and event management system (SIEM) for threat analysis and detection.
---
= Simulate suspicious user behavior in NetApp Ransomware Resilience
:icons: font
:imagesdir: ./media/

[.lead]
When you configure user activity monitoring in NetApp Ransomware Resilience, you can run a test script to simulate suspicious user behavior events. 

// wording

== About the script

The test script is available when you enable user activity monitoring on a machine. The script can be run with shell or Python.

You should run the script on a volume of a storage VM where you've created a data collector. The script should be run on test data on a volume that includes at least 100 files in multiple sub-directories; you can programmatically generate these files with the script. Pause the data collector before creating the test data then resume it after. 

== Considerations 

* The script simulates user encryption events. It can only be run on Linux systems. 
* If the system uses NFSv4.1, you must be running ONTAP 9.15.1 or later.
* You can run the script on the system with user activity agent. You can also run  copy the script and run it there.
* You can run the script as a shell script or with Pyton. 
+
[NOTE]
There are <<pre-requisites>> to the Python script. To avoid these, use the shell script. 

== Before you begin

You should have link:suspicious-user-activity.html[a user activity collector] on the system where you want to conduct the test. 

[[pre-requisites]]
=== Requirements for Python script

To run the script in Python, you must have:

* link:https://www.python.org/[Installed Python version 3.5.2 or later^]
* link:https://bootstrap.pypa.io/[Installed pip^]
* Installed the PyCryptodome library. With pip, run the command, `pip install pycryptodome`.

[TIP]
You can check your Python version with the command `python --version`. You can test the pip installation with the command `pip --version`. You can test the PyCryptodome installation with the command `running pip show pycryptodome`.

== Simulate an encryption event


.Prepare the system
. Mount the target volume where the samples files will be created to the Linux machine. You can mount either an NFS or CIFS export.
[role="tabbed-block"]
====
.NFS
--
```
mount -t nfs -o vers=4.0 10.193.177.158:/svmvol1 /mntpt
mount -t nfs -o vers=4.0 Vserver data IP>:/nfsvol /destinationlinuxfolder
```
--
.CIFS
--
mount -t cifs //10.193.77.91/sharedfolderincluster /root/destinationfolder/ -o username=raisa
--
====
. Protect the link:suspicious-user-activity.html[target volume].
. Pause the data collector.
+
In Ransomware Resilience, select **Settings** then in the User detection monitoring tile, select **Manage**. In the Data collector tab, select the data collector for the storage VM then **Pause**. 
. Add files to be encrypted. You can either manually copy the files to be encrypted into the target folder/Volume, or use one of the included scripts to programmatically create the files. You must add a minimum of 100 files. 
+
To programatically create the files:
[role="tabbed-block"]
====
.Shell
--
. Log into the Agent box.
. Mount an NFS or CIFS share from the SVM of the filer to the UEBA Agent machine. Cd to that folder.
. Copy the script from Agent installation directory (%AGENT_INSTALL_DIR/ agent/install/ransomware_simulation/shell/create_dataset.sh) to the target mount location.
. Execute the `./create_dataset.sh` command using the scripts within the mounted directory to create the test dataset folder and files. This creates a 100 (non-empty) files with different extensions inside the mounted folder under a directory named "test_dataset".
--
.Python
--
. Log into the Agent box.
. Mount an NFS or CIFS share from the storage VM of the filer to the Agent machine. Change the working directory to the appropriate volume for testing. 
. Copy the script from Agent installation directory to the target volume: `%AGENT_INSTALL_DIR/agent/install/ransomware_simulation/python/create_dataset.py`.
. Create the test dataset: `python create_dataset.py`.
+
This creates a 100 (non-empty) files with different extensions inside the mounted folder under a directory named "test_dataset".
--
====
. Resume the collector. 

.Simulate the attack 
[role="tabbed-block"]
====
.Shell
--
. Copy the script from Agent installation directory to the target mount location: `%AGENT_INSTALL_DIR/agent/install/ransomware_simulation/shell/simulate_attack.sh`.
. Execute the script in the the mounted directory to encrypt the test dataset: `./simulate_attack.sh`.
--
.Python
--
. Copy the script from Agent installation directory to the target mount location: `%AGENT_INSTALL_DIR/agent/install/ransomware_simulation/shell/simulate_attack.sh`.
. Execute the script to encrypt the data: `python simulate_attack.py` in "test_dataset".
--
====

.Generate an alert in Ransomware Resilience
Once the simulator script execution has finished, an alert will be seen on the Web UI within a few minutes. Ransomware Resilience detects Encryption (User Behaviour) patterns based on user behaviour.
Triggering alert multiple times
Ransowmare Resilience learns user behavior and will not generate alerts on repeated Encryption (User Behaviour) attacks within 24 hours for the same user.
To generate a new alert with a different user, please follow the same steps again (creating test data and then encrypting the test data).

Data Breach and Data Destruction Alert:
1.	Mount the protected volume (sudo mount -t nfs -o rw,hard,nfsvers=4.0,proto=tcp,noac,actimeo=0,lookupcache=none 10.196.61.101:/vs0_vol01 /root/vol)
2.	Pause Data collector from the RR UI (Settings->user activity->manage->data collectors): Wait for it to Pause
3.	Write data
1.	mkdir -p ./data5k; seq -w 1 5000 | xargs -n1 -P2 -I{} bash -c 'sz=$((RANDOM%16+5)); LC_ALL=C tr -dc "A-Za-z0-9\n" < /dev/urandom | head -c "$((sz*1024))" > ./data5k/file_{}.txt'
4.	Resume collector from RPS UI: Wait for it to be running
5.	Bulk Read
1.	Clear cache: sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches >/dev/null
2.	find ./data5k -type f -print0 | xargs -0 -n1 -P4 -I{} dd if={} of=/dev/null bs=1M iflag=direct status=none
6.	Databreach alert should show up in some time
7.	DD alert: User must be active for > 7 days.
1.	Delete command as a dummy user: sudo setpriv --reuid 60001 --regid 60001 --groups 60001 bash -lc 'id -u; id -g; id -G; rm -rf data5k5'
2.	OR just do rm -rf <dir to be deleted>
