---
sidebar: sidebar
permalink: task-users-manage.html
keywords: user activity detection, 
summary: After creating the user activity connector in NetApp Ransomware Resilience, you can block and unblock users and exclude users from notifications. 
---
= Manage user blocking and alerts in NetApp Ransomware Resilience
:icons: font
:imagesdir: ./media/

[.lead]
After creating the user activity connector in NetApp Ransomware Resilience, you can block and unblock users when you experience ransomware events and evaluate them. You can also selectively exclude users from ransomware alerts if you are certain their actions aren't attacks.

You must have link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#create-a-user-activity-agent[configured a user activity agent, enabled a policy with user activity detection, and created a user directory connector] before creating an automated policy.

[TIP]
You can link:task-automate-user-activity.html[automate responses] to user activity detection events. 

== Manage blocked users

You can block users when you believe they're responsible for malicious activity. 

.Block users
. In Ransomware Resilience, select **Settings**. 
. In the Settings dashboard, locate the User activity monitoring tile then select **Manage**. 
. Select the **Users** tab. 
. Select **Block users**. 
. Select the duration of the blocking: it can be one hour up to 24 hours or permanent. 
. Select the checkbox next to the names of the users you want to block. 
. Select **Block**. 

.Modify the blocked users list
. In Ransomware Resilience, select **Settings**. 
. In the Settings dashboard, locate the User activity monitoring tile then select **Manage**. 
. Select the **Users** tab. 
. Select **Edit user blocking**. 
. Choose the modification. To modify the duration of the blocking, select **Time period for blocked users** then modify the duration. To remove users from the blocked user list, select **Unblock users**. 
. Select the checkbox next to the name of the block user whose status you want to change. 
. Select **Save**. 

== Manage user alerts

If there are certain trusted users whose behavior might trigger user behavior alerts, you can exclude them from alerts. 

.Exclude users from alerts
. In Ransomware Resilience, select **Settings**. 
. In the Settings dashboard, locate the User activity monitoring tile then select **Manage**. 
. Select the **Excluded from monitoring** tab. 
. To review individual users in the UI, choose **Select manually**. To upload a list of excluded users, select **Upload**. 
.. If you selected **Select manually**, select the checkbox next to the names of the specific users you want to exclude. 
.. If you select **Upload**, download the CSV or JSON file that includes the list of all the users. Select **Download** to access the list. 
+
On your local machine, review the file. Remove the names of all users that you want to maintain detection for. When the list includes only the names of users you want to exclude from detection, save it.
+
In Ransomware Resilience, select **Upload**. Locate and upload the file. 
. Select **Add** to complete adding the users to the exlcusion list. 
. In the **Excluded users** tab, the names of the users removed from user behavior detection alerts now display in the dashboard. 

[TIP]
You can also exclude a user directly from an alert. For more information, see link:rp-use-alert.html[Respond to ransomware alerts].

.Remove users from the excluded user list
. In the Settings dashboard, locate the User activity monitoring tile then select **Manage**. 
. Select the **Excluded from monitoring** tab.
. Select **Add**.
. To exlcude individual users from the UI, choose **Select manually**.
. Locate the name of the user you want to remove from the excluded user select. Select the action menu (`...`) on the row with the user's name then **Remove**.
. In the dialog, select **Remove** to confirm you want to remove the selected users. 

== Next steps

* link:task-automate-user-activity.html[Automate responses to user activity detection events] 