---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ransomware protection
summary: Learn what's new in BlueXP ransomware protection.
---

= Release notes: What's new with BlueXP ransomware protection preview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP ransomware protection preview.

// tag::whats-new[]
== 6 October 2023 

The BlueXP ransomware protection service is an orchestration service for ransomware protection, detection, and recovery. 

For the preview version, the service For the preview version, the service protects application-based workloads of Oracle, MySQL, VM datastores, and file shares on on-premises NAS storage (using the NFS protocol) across BlueXP accounts individually and backs up data to Amazon Web Services (AWS) cloud storage. 


BlueXP ransomware protection encompasses the following strategies:

* *Identify* all application-based workloads in NetApp on-premises, NAS working environments in BlueXP, across BlueXP accounts, workspaces, and BlueXP Connectors. The service then categorizes the data priority and provides recommendations to you for ransomware protection improvements.

* *Protect* high priority data by creating a backup in AWS S3 cloud storage. 

* *Detect* data anomalies that might result in ransomware attacks. 

* *Respond* to potential ransomware attacks by automatically initiating a NetApp Snapshot. 

* *Recover* data in the event of an attack to accelerate application uptime by orchestrating several NetApp technologies. 

https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html[Learn about BlueXP ransomware protection].

// end::whats-new[] 

