---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ransomware protection
summary: Learn what's new in Ransomware Protection.
---

= What's new with Ransomware Protection
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in Ransomware Protection.

// tag::whats-new[]
== 7 November 2022

=== New panels to display your overall Ransomware Protection Score and Recommended Actions

These two new panels work together to identify how resilient your data is to a ransomware attack, and what you can do to improve your score. The Ransomware Protection Score panel shows the overall score and the areas of cybersecurity where potential issues exist. The Recommended Actions panel lists the potential actions you can take to improve your resilience to a ransomware attack, and provides a link to investigate the issue so you can apply the actions where necessary. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#ransomware-protection-score-and-recommended-actions[Learn more here^].

== 6 September 2022

=== New panel to display ransomware incidents detected on your clusters

The _Ransomware incidents_ panel shows ransomware attacks that have occurred on your systems. Current support is for on-premises ONTAP clusters that are running Autonomous Ransomware Protection (ARP). ARP uses workload analysis in NAS (NFS and SMB) environments to proactively detect and warn about abnormal activity that might indicate a ransomware attack. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#ransomware-incidents-detected-on-your-systems[Learn more here^].

== 7 August 2022

=== New panel to show security vulnerabilities on your clusters

The _Storage system vulnerabilities_ panel shows the total number of high, medium, and low security vulnerabilities that the Active IQ Digital Advisor tool has found on each of your ONTAP clusters. High vulnerabilities should be looked at immediately to make sure your systems are not open for attack. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#storage-system-vulnerabilities[Go here for details^].

=== New panel to show immutable scanned files

The _Critical data immutability_ panel shows the number of items in your working environments that are being protected from modification and deletion on WORM storage by using ONTAP SnapLock technology. This allows you to view how much of your data has an immutable copy so you can better understand your backup and recovery plans against ransomware. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#data-in-your-volumes-that-are-being-protected-using-snaplock[Go here for details^].
// end::whats-new[]

== 12 June 2022

=== NAS file system auditing status is now tracked for your ONTAP storage VMs

An alert is added to the _Cyber Resilience Map_ if less than 40% of the storage VMs in the working environment have file system auditing enabled. You can view the exact number of SVMs that are not tracking and logging SMB and NFS events into an audit log in the _Harden your ONTAP environment_ panel. Then you can decide whether to enable auditing on those SVMs.

=== Alerts are now displayed when on-box anti-ransomware is not active for your volumes

This information was being reported for on-prem ONTAP systems in the _Harden your ONTAP environments_ panel previously, but now an alert is reported in the _Cyber Resilience Map_ when the on-box anti-ransomware feature is turned on in less than 40% of volumes so you can view this information in the Dashboard.

=== FSx for ONTAP systems are now tracked for enabling volume snapshots

The _Harden your ONTAP environments_ panel now provides the status of Snapshot copies for volumes on your FSx for ONTAP systems. When less than 40% of the volumes are being protected by snapshots, you will also get an alert in the _Cyber Resilience Map_.

== 11 May 2022

=== New panel to track the security hardening of your ONTAP environments

A new panel _Harden your ONTAP environments_ provides the status of certain settings in your ONTAP systems that track how secure your deployment is according to the https://www.netapp.com/pdf.html?item=/media/10674-tr4569.pdf[NetApp Security Hardening Guide for ONTAP Systems^] and to the https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html[ONTAP anti-ransomware feature^] that proactively detects and warns about abnormal activity.

You can review the recommendations and then decide how you want to address the potential issues. You can follow the steps to change the settings on your clusters, defer the changes to another time, or ignore the suggestion. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#status-of-ontap-systems-hardening[Go here for details].

=== New panel to show how different categories of data are being protected using Cloud Backup

This new _Backup Status_ panel shows how comprehensively your most important categories of data are backed up in case you need to recover because of a ransomware attack. This data is a visual representation of how many items of a specific category in an environment are backed up by Cloud Backup. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#backup-status-of-your-critical-business-data[Go here for details].

== 15 March 2022

=== New panel to track the permissions status of your business critical data

A new panel _Business critical data permissions analysis_ shows the permissions status of data that is critical for your business. That way you can quickly assess how well you are protecting your business-critical data. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#status-of-permissions-on-your-critical-business-data[Go here for details].

=== Open Permissions area now includes OneDrive and SharePoint accounts

The Open Permissions area in the Ransomware Protection Dashboard now includes the permissions that exist for files that are being scanned in OneDrive accounts and SharePoint accounts.

== 9 February 2022

=== New Ransomware Protection service

The new Ransomware Protection service enables you to view relevant information about cybersecurity and assess how resilient your data is to a cyber attack. It also provides you with a list of alerts and remediations for making your data more secure.

link:concept-ransomware-protection.html[Learn more about this new service].
