---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ransomware protection
summary: Learn what's new in BlueXP ransomware protection.
---

= Release notes: What's new with BlueXP ransomware protection preview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP ransomware protection preview.

// tag::whats-new[]

//== 31 January 2024
//This release of the BlueXP ransomware protection includes the following updates: 

//* Recovery process enhancements
//* Protection policy management features were added for this release. 
//* Automatic backup to NetApp StorageGRID
//* Immutability on secondary storage using DataLock features
//* Additional features to investigate potential attacks 

== 6 October 2023 

The BlueXP ransomware protection service is an orchestration service for ransomware protection, detection, and recovery. 

For the preview version, the service protects application-based workloads of Oracle, MySQL, VM datastores, and file shares on on-premises NAS storage (using the NFS protocol) across BlueXP accounts individually and backs up data to Amazon Web Services (AWS) cloud storage. 

The BlueXP ransomware protection service provides full use of several NetApp technologies so that your data security administrator or security operations engineer can accomplish the following goals:

* View ransomware protection on all your workloads at a glance.
* Gain insight into ransomware protection recommendations
* Improve protection posture based on BlueXP ransomware protection recommendations.
* Assign ransomware protection policies to protect your top workloads and high-risk data against ransomware attacks.
* Monitor the health of your workloads against ransomware attacks looking for data anomalies.
* Quickly assess the impact of ransomware incidents on your workload. 
* Recover from ransomware incidents intelligently by restoring data and ensuring that reinfection from stored data does not occur. 

https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html[Learn about BlueXP ransomware protection].

// end::whats-new[] 

