---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ransomware protection, bluexp, anti-ransomware, cyber attack
summary: Learn what's new in BlueXP ransomware protection.
---

= Release notes: What's new with BlueXP ransomware protection preview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP ransomware protection preview.

// tag::whats-new[]

== 15 May 2024

This release is the general availability release of BlueXP ransomware protection. It includes the following updates: 

* *Licensing updates*: You can sign up for a 90-day free trial, purchase a pay-as-you-go subscription for 1, 2, or 3 years with Amazon Web Services Marketplace, or bring your own NetApp license.  

+
link:rp-start-licenses.html[Learn more about setting up licensing].

//https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html[Learn more about setting up licensing].

* *CIFS protocol*: The service now supports on-premises ONTAP and Cloud Volumes ONTAP in AWS working environments using both NFS and CIFS protocols. The previous release supported only the NFS protocol. 

* *Workload details*: This release now provides more details in the workload information from the Protection pages for improved workload protection assessment. From the workload details, you can change the workload name, change the workload importance, review the currently assigned policy, and review the configured backup destinations.  
+
link:rp-use-protect.html[Learn more about viewing workload details].

//https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html[Learn more about viewing workload details in the Protection pages]. 

* *Application-consistent and VM-consistent protection and recovery*: You can now perform application-consistent protection with NetApp SnapCenter Software and VM-consistent protection with SnapCenter Plug-in for VMware vSphere, achieving a quiescent and consistent state to avoid potential data loss later if recovery is needed. If recovery is required, you can restore the application or VM back to its previous state and last transaction. 
+
link:rp-use-protect.html[Learn more about enabling workload-consistent protection with SnapCenter].

//https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html[Learn more about protecting workloads].

* *Ransomware protection strategies*: If the existing policies do not meet your business needs, you can create a ransomware protection strategy, which can include the following policies: 

** Detection policy governed by BlueXP ransomware protection
** Snapshot policy governed by other NetApp products
** Backup policy governed by other NetApp products

+
link:rp-use-protect.html[Learn more about protecting workloads and creating protection strategies].

//https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html[Learn more about protecting workloads].

* *Snapshot copy locking on primary storage*: Enable this to use DataLock to lock the Snapshot copies on primary storage so that they cannot be modified or deleted for a certain period of time even if a ransomware attack manages its way to the backup storage destination. 

+
link:rp-use-protect.html[Learn more about protecting workloads].

//https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html[Learn more about protecting workloads].

//* *Settings option*: You can now set up backup destinations in BlueXP ransomware protection Settings. link:rp-use-settings.html[Learn more about configuring Settings options]. 

* *Enable threat detection* using third-party security and event management (SIEM) or extended detection and response (XDR) server. The Dashboard now shows a new recommendation to "Enable threat detection" which can be configured on the Settings page. 
+
link:rp-use-settings.html[Learn more about configuring Settings options].  

* *Download reports* from the Dashboard, Protection, Alerts, and Recovery pages. 
+
link:rp-use-dashboard.html[Learn more about downloading reports from the Dashboard and other pages].



== 5 March 2024
This preview release of BlueXP ransomware protection includes the following updates: 


* *Protection policy management*: In addition to using predefined policies, you can now create, change, and delete policies. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html[Learn more about managing policies].

* *Immutability on secondary storage (DataLock)*: You can now make the backup immutable in secondary storage using NetApp DataLock technology in the object store. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html[Learn more about creating protection policies]. 


* *Automatic backup to NetApp StorageGRID*: In addition to using AWS, you can now choose StorageGRID as your backup destination. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html[Learn more about configuring backup destinations].
* *Additional features to investigate potential attacks*: You can now view more forensic details to investigate the detected potential attack. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html[Learn more about responding to a detected ransomware alert]. 
* *Recovery process*. The recovery process was enhanced. Now, you can recovery volume by volume, all volumes for a workload, or even a few files from the volume all in a single workflow. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-recover.html[Learn more about recovering from a ransomware attack (after incidents have been neutralized)]. 

https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html[Learn about BlueXP ransomware protection].

== 6 October 2023 

The BlueXP ransomware protection service is a SaaS solution for protecting data, detecting potential attacks, and recovering data from a ransomware attack. 

For the preview version, the service protects application-based workloads of Oracle, MySQL, VM datastores, and file shares on on-premises NAS storage as well as Cloud Volumes ONTAP on AWS (using the NFS protocol) across BlueXP accounts individually and backs up data to Amazon Web Services cloud storage. 

The BlueXP ransomware protection service provides full use of several NetApp technologies so that your data security administrator or security operations engineer can accomplish the following goals:

* View ransomware protection on all your workloads at a glance.
* Gain insight into ransomware protection recommendations
* Improve protection posture based on BlueXP ransomware protection recommendations.
* Assign ransomware protection policies to protect your top workloads and high-risk data against ransomware attacks.
* Monitor the health of your workloads against ransomware attacks looking for data anomalies.
* Quickly assess the impact of ransomware incidents on your workload. 
* Recover from ransomware incidents intelligently by restoring data and ensuring that reinfection from stored data does not occur. 

https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html[Learn about BlueXP ransomware protection].

// end::whats-new[] 

