---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ransomware protection
summary: Learn what's new in BlueXP ransomware protection.
---

= Release notes: What's new with BlueXP ransomware protection preview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP ransomware protection preview.

// tag::whats-new[]
== 6 October 2023 

The BlueXP ransomware protection service has been redesigned as an orchestration service for ransomware protection, detection, and recovery. 

For the preview version, the service protects application-based workloads on on-premises NAS storage across all BlueXP accounts and working environments and backs up data to Amazon Web Services (AWS) or Microsoft Azure cloud storage. 

BlueXP ransomware protection encompasses the following strategies:

* *Identify* all application-based workloads in NetApp on-premises, NAS working environments in BlueXP, across all BlueXP accounts, workspaces, and BlueXP Connectors. The service then categorizes the data priority and provides recommendations to you for ransomware protection improvements.

* *Protect* high priority data by creating an immutable backup in AWS or Azure Blob cloud storage. 

* *Detect* data anomalies using AI technologies in secondary cloud storage that might result in ransomware attacks. 

* *Respond* to potential ransomware attacks by automatically initiating a tamper-proof NetApp Snapshot that is locked so that the copy cannot be deleted accidentally or maliciously (with cloud-based DataLock features enabled). With cloud-based NetApp DataLock enabled, your backup data will stay immutable and protected end to end from ransomware attacks at the source and in the destination.

* *Recover* data in the event of an attack to accelerate application uptime by orchestrating several NetApp technologies. 

https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html[Learn about BlueXP ransomware protection].

// end::whats-new[] 

