=== Enable data classification and scan for personally identifiable information (PII)
With this release, you can enable BlueXP classification, a core component of the BlueXP family, to scan and classify data in your file share workloads. Classifying data helps you identify whether your data includes personal or private information, which can increase security risks. This process also impacts workload importance and helps you ensure that you are protecting workloads with the right level of protection. 

Scanning for PII data in BlueXP ransomware protection is generally available to customers who deployed BlueX classification. BlueXP classification is available as part of the BlueXP platform at no extra charge and can be deployed on-premises or in the customer cloud. 

BlueXP classification can be also deployed as a SaaS model as part of a Technology Preview. To enable Preview features, use the BlueXP ransomware protection *Settings* option. If you enable Preview, a "Preview" label appears next to the *Privacy exposure* column on the Protection page along with other locations. 

//Refer to link://rp-use-settings-html[Configure BlueXP ransomware protection settings]. 
Refer to https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html[Configure BlueXP ransomware protection settings]. 

To initiate scanning, on the Protection page, click *Identify exposure* in the Privacy exposure column. 

//link:rp-use-protect-classify.html[Scan for personally identifiable sensitive data with BlueXP classification].

https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html[Scan for personally identifiable sensitive data with BlueXP classification].

=== Try upcoming Preview features before they are released
You can now try out some features labeled "Preview" before they are released. To do so, use the *Settings* option to show these features, which are tagged with a "Preview" label.
//+
//For details, refer to link:rp-use-settings.html[Configure BlueXP ransomware protection settings]. 

https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html[Learn more about configuring BlueXP ransomware protection settings].

=== SIEM integration with Microsoft Sentinel
You can now send data to your security and event management system (SIEM) for threat analysis and detection using Microsoft Sentinel. Previously, you could select the AWS Security Hub or Splunk Cloud as your SIEM.

//For details, refer to link:rp-use-settings.html[Configure BlueXP ransomware protection settings]. 

https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html[Learn more about configuring BlueXP ransomware protection settings]. 

//* *Configure cyber vault*: With this release, you can lock immutable and indelible snapshots on a NetApp cyber vault, an air-gapped environment that is logically separated from primary networks and systems. The snapshots cannot be deleted until the retention policy on those snapshots expires. By moving data to a cyber vault, bad actors have no access to the data. 
//+
//Learn more about the https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html[ONTAP cyber vault].

//* *Google Cloud Platform Marketplace*: BlueXP ransomware protection is now available on GCP Marketplace. You can activate the service through the BlueXP *View payment methods* option. 
//+
//For details, refer to link:rp-start-licenses.html[Set up licensing]. 
//https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html[Learn more about setting up BlueXP ransomware protection licenses]. 

=== Free trial now 30 days
With this release, new deployments of BlueXP ransomware protection now have 30 days for a free trial. Previously, BlueXP ransomware protection provided 90 days as a free trial. If you are already in the 90-day free trial, that offer continues for the 90 days. 

=== Restore application workload at the file level for Podman
Before you restore an application workload at the file level, you can now view a list of files that might have been impacted by an attack and identify those you want to restore. Previously, if the BlueXP Connectors in an organization (previously an account) were using Podman, this feature was disabled. It is now enabled for Podman. You can let BlueXP ransomware protection choose the files to restore, you can upload a CSV file that lists all the files impacted by an alert, or you can manually identify which files you want to restore. 

//link:rp-use-recover.html[Learn more about recovering from a ransomware attack].
https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-recover.html[Learn more about recovering from a ransomware attack].

//* *Isolate impacted data in a quarantine environment*: 
//Before starting data recovery for workloads, you can choose if you would like to quarantine infected data for further analysis post recovery.
//+
//link:rp-use-recover.html[Learn more about recovering from a ransomware attack].
//https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-recover.html[Learn more about recovering from a ransomware attack].
