=== Security risk assessment from Digital Advisor
BlueXP ransomware protection now gathers information about high and critical security risks related to a cluster from NetApp Digital Advisor. If any risk is found, BlueXP ransomware protection provides a recommendation in the Dashboard's *Recommended actions* pane: "Fix a known security vulnerability on the cluster <name>." From the recommendation on the Dashboard, clicking *Review and fix* suggests to review Digital Advisor and a Common Vulnerability & Exposure (CVE) article to resolve the security risk. If there are multiple security risks, review information in Digital Advisor. 

Refer to https://docs.netapp.com/us-en/active-iq/index.html[Digital Advisor documentation^].

=== Back up to Google Cloud Platform
With this release, you can set a backup destination to a Google Cloud Platform bucket. Previously, you could add backup destinations only to NetApp StorageGRID, Amazon Web Services, and Microsoft Azure. 
//+
//For details, refer to link:rp-use-settings.html[Configure BlueXP ransomware protection settings]. 

https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html[Learn more about configuring BlueXP ransomware protection settings].

=== Support for Google Cloud Platform
The service now supports Cloud Volumes ONTAP for Google Cloud Platform for storage protection. Previously, the service supported only Cloud Volumes ONTAP for Amazon Web Services and Microsoft Azure along with on-premises NAS.

https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html[Learn about BlueXP ransomware protection and supported data sources, backup destinations, and working environments]. 
//link:concept-ransomware-protection.html[Learn about BlueXP ransomware protection and supported data sources, backup destinations, and working environments]. 

=== Role-based access control
You can now limit access to specific activities with role-based access control (RBAC). BlueXP ransomware protection uses two roles from BlueXP: BlueXP Account Admin and Non-Account Admin (Viewer).
//+
//For details about the actions that each role can perform, see link:rp-reference-roles.html[Role-based access control privileges].

For details about the actions that each role can perform, see https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html[Role-based access control privileges].
