=== Detect anomalous user behavior using Data Infrastructure Insights Storage Workload Security

With this release, you can use Data Infrastructure Insights Storage Workload Security to detect anomalous user behavior in your storage workloads. This feature helps you identify potential security threats and block potentially malicious users to protect your data.

For details, refer to https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html[Respond to a detected ransomware alert]. 

Before you use Data Infrastructure Insights Storage Workload Security to detect anomalous user behavior, you need to configure the option by using the BlueXP ransomware protection *Settings* option.

Refer to https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-settings.html[Configure BlueXP ransomware protection settings]. 

=== Select workloads to discover and protect

With this release, you can now do the following: 

* Within each Connector, select the working environments where you want to discover workloads. You might benefit from this feature if you want to protect specific workloads in your environment and not others. 
* During workload discovery, you can enable automatic discovery of workloads per Connector. This feature lets you select the workloads that you want to protect. 
* Discover newly created workloads for previously selected working environments. 

Refer to https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-discover.html[Discover workloads]. 
