=== Detect anomalous user behavior using Data Infrastructure Insights Storage Workload Security

With this release, you can use Data Infrastructure Insights Storage Workload Security to detect anomalous user behavior in your storage workloads. This feature helps you identify potential security threats and block potentially malicious users to protect your data.

For details, refer to https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html[Respond to a detected ransomware alert]. 

Before you use Data Infrastructure Insights Storage Workload Security to detect anomalous user behavior, you need to configure the option by using the BlueXP ransomware protection *Settings* option.

Refer to https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-settings.html[Configure BlueXP ransomware protection settings]. 

=== Select workloads to discover and protect

With this release, you can now do the following: 

* Within each Connector, select the working environments where you want to discover workloads. You might benefit from this feature if you want to protect specific workloads in your environment and not others. 
* During workload discovery, you can enable automatic discovery of workloads per Connector. This feature lets you select the workloads that you want to protect. 
* Discover newly created workloads for previously selected working environments. 

//Refer to link://rp-start-discover-html[Discover workloads]. 
Refer to https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-discover.html[Discover workloads]. 


//=== Configure cyber vault
// With this release, you can lock immutable and indelible snapshots on a NetApp cyber vault, an air-gapped environment that is logically separated from primary networks and systems. The snapshots cannot be deleted until the retention policy on those snapshots expires. By moving data to a cyber vault, bad actors have no access to the data. 
//+
//Learn more about the https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html[ONTAP cyber vault].

//=== Support for Google Cloud Platform Marketplace
//BlueXP ransomware protection is now available on GCP Marketplace. You can activate the service through the BlueXP *View payment methods* option.

//+
//For details, refer to link:rp-start-licenses.html[Set up licensing]. 
//https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-licenses.html[Learn more about setting up BlueXP ransomware protection licenses]. 

//=== Isolate impacted data in a quarantine environment

//Before starting data recovery for workloads, you can choose if you would like to quarantine infected data for further analysis post recovery.
//+
//link:rp-use-recover.html[Learn more about recovering from a ransomware attack].
//https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-recover.html[Learn more about recovering from a ransomware attack].
