=== Security risk assessment from Digital Advisor
BlueXP ransomware protection now gathers information about high and critical cluster security risks from NetApp Digital Advisor. If a risk is found, BlueXP ransomware protection displays this recommendation in the Dashboard *Recommended actions* pane: "Fix a known security vulnerability on the cluster <name>." From the Dashboard recommendation, select *Review and fix* to review Digital Advisor and the related Common Vulnerability & Exposure (CVE) article. If there are multiple security risks, review the details in Digital Advisor. 

Refer to https://docs.netapp.com/us-en/active-iq/index.html[Digital Advisor documentation^].

=== Back up to Google Cloud Platform
With this release, you can set a backup destination to a Google Cloud Platform bucket. Previously, you could add backup destinations only to NetApp StorageGRID, Amazon Web Services, and Microsoft Azure. 

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-backup-destination.html[Learn more about configuring BlueXP ransomware protection settings].

=== Support for Google Cloud Platform
The service now supports Cloud Volumes ONTAP for Google Cloud Platform for storage protection. Previously, the service supported only Cloud Volumes ONTAP for Amazon Web Services and Microsoft Azure along with on-premises NAS.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html[Learn about BlueXP ransomware protection and supported data sources, backup destinations, and working environments]. 
//link:concept-ransomware-resilience.html[Learn about BlueXP ransomware protection and supported data sources, backup destinations, and working environments]. 

=== Role-based access control
You can now limit access to specific activities with role-based access control (RBAC). BlueXP ransomware protection uses two roles from BlueXP: BlueXP Account Admin and Non-Account Admin (Viewer).
//+
//For details about the actions that each role can perform, see link:rp-reference-roles.html[Role-based access control privileges].

For details about the actions that each role can perform, see https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html[Role-based access control privileges].
