=== Readiness drill reports

With this release, you can review ransomware attack readiness drill reports. A readiness drill enables you to simulate a ransomware attack on a newly created, sample workload. Then, investigate the simulated attack and recover the sample workload. This feature helps you know that you are prepared in the event of an actual ransomware attack by testing alert notification, response, and recovery processes. 

For details, refer to link:rp-start-simulate.html[Conduct a ransomware attack readiness drill]. 

//For details, refer to https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html[Conduct a ransomware attack readiness drill].

=== New role-based access control roles and permissions

Previously, you could assign roles and permissions to users based on their responsibilities, which helps you manage user access to BlueXP ransomware protection. With this release, there are two new roles and updated permissions. The new roles are:

* Ransomware protection admin
* Ransomware protection viewer

For details about permissions, refer to link:rp-reference-roles.html[Role-based access to features]. 

//For details about permissions, refer to https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html[BlueXP ransomware protection role-based access to features].






