=== BlueXP ransomware protection is now NetApp Ransomware Resilience
 
BlueXP ransomware replication has been renamed to NetApp Ransomware Resilience. 

=== BlueXP is now NetApp Console
 
BlueXP has been renamed and redesigned to better reflect its role in managing your data infrastructure.  
 
The NetApp Console provides centralized management of storage and data services across on-premises and cloud environments at enterprise grade—delivering real-time insights, faster workflows, and simplified administration.
 
For details on what has changed, see the https://docs.netapp.com/us-en/bluexp-relnotes/index.html[NetApp Console release notes].

=== Data breach protection 

=== SIEM 

//

=== Isolated recovery environment (private preview)

Ransomware Resilience now supports an isolated recovery environment. With the isolated recovery environment, Ransomware Resilience isolates infected workloads to identify encryption and remove malware; it also recommends recovery options to increase the recovery time and reduce the amount of data loss. The isolated recovery environment provides a guided, step-by-step restoration process. This approach delivers a clean, malware-free workload restoration that prevents reinfection and minimizes data loss.

For more information, see link:isolated-recovery-task.html[Restore files safely with the isolated recovery environment].