=== SAN workload support 
This release includes support for SAN workloads in BlueXP ransomware protection. You can now protect SAN workloads in addition to NFS and CIFS workloads.

=== Improved workload protection 
This release includes an improved workflow for protecting workloads with or without data protection. The update simplifies the process of protecting workloads by guiding you through the steps, making it easier to protect your valuable resources.

//For details, refer to link:rp-use-protect.html[Protect workloads]. 

//For details, refer to https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html[Protect workloads].

=== Email notifications 
If BlueXP ransomware protection detects a possible attack, a notification appears in the BlueXP Notifications and an email is sent to the email address that you configured indicating a potential ransomware attack. The service also immediately initiates a snapshot. 

At this point, you should view the email, which lists the severity and resources impacted and look at the potential risk in the BlueXP ransomware protection *Alerts* tab.

If you configured a SIEM in BlueXP ransomware protection, the service sends alert details to your SIEM system. 

//For details, refer to link:rp-use-alert.html[Handle detected ransomware alerts]. 

//For details, refer to https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html[Handle detected ransomware alerts].
