=== Support for Amazon FSx for NetApp ONTAP 

This release supports Amazon FSx for NetApp ONTAP. This feature helps you protect your FSx for ONTAP workloads with BlueXP ransomware protection. 

FSx for ONTAP is a fully managed service that provides the power of NetApp ONTAP storage in the cloud. It provides the same features, performance, and administrative capabilities that you use on-premises with the agility and scalability of a native AWS service.  

The following changes were made to the BlueXP ransomware protection workflow:

* Discovery includes workloads in FSx for ONTAP 9.15 working environments.
* The Protection tab shows workloads in FSx for ONTAP environments. In this environment, you should perform backup operations using the FSx for ONTAP backup service. You can restore these workloads using BlueXP ransomware protection snapshots. 
+
TIP: Backup policies for a workload running on FSx for ONTAP can't be set in BlueXP. Any existing backup policies set in Amazon FSx for NetApp ONTAP remain unchanged.
* Alert incidents show the new FSx for ONTAP working environment. 

//For details, refer to link:rp-concept-ransomware-protection.html[Learn about BlueXP ransomware protection and working environments]. 

For details, refer to https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-concept-ransomware-protection.html[Learn about BlueXP ransomware protection and working environments].

//For information about the supported options, refer to the link:rp-reference-limitations.html[BlueXP ransomware protection limitations].

For information about the supported options, refer to the https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html[BlueXP ransomware protection limitations].

