=== BlueXP ransomware protection is now NetApp Ransomware Resilience
 
BlueXP ransomware replication has been renamed to NetApp Ransomware Resilience. 

=== BlueXP is now NetApp Console
 
The NetApp Console, built on the enhanced and restructured BlueXP foundation, provides centralized management of NetApp storage and NetApp Data Services across on-premises and cloud environments at enterprise grade—delivering real-time insights, faster workflows, and simplified administration, that is highly secure and compliant.
 
For details on what has changed, see the link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html[NetApp Console release notes].

=== Data breach protection 

The process to identify potential security threats from anomalous behavior has changed and is managed entirely in Ransomware Resilience. With data breach protection, you can configure alerts for potential malacious user activity and block users to protect your data. 

include::../_include/workload-security-note.adoc[]

For more information, see xref:rp-use-settings.html#enable-suspicious-user-activity-detection[Enable suspicious user activity detection] and link:rp-use-alert.html#view-anomalous-user-behavior[View anomalous user behavior].

==== New user role for data breach detection 

To configure data breach protection, you must have a user role with the new Ransomware Resilience data breach administrator role in the NetApp Console. You can view user-level data breach information with the Ransomware Resilience data breach administrator role or the Ransomware Resilience data breach viewer role. 

=== SIEM 

Information forthcoming from engineering. 