=== Display of unsupported clusters in BlueXP ransomware protection

With this release, BlueXP ransomware protection discovers the following unsupported volume workloads as working environments (both with and without a BlueXP Connector). This helps you identify and resolve issues with your workloads.

* Amazon FSx for ONTAP working environments that are not managed by a BlueXP Connector
* Azure NetApp Files 
* Cloud Volumes ONTAP working environments that are not managed by a BlueXP Connector
* Cloud Volumes Service 
* E-series 
* Google Cloud Platform (GCP)
* ONTAP 9.11.1 and earlier versions that are not managed by a BlueXP Connector 
* ONTAP Direct on-premises clusters that are not managed by a BlueXP Connector 
* StorageGRID 

You can view the unsupported working environments during initial discovery and later from the *Workload discovery* option in the Settings page. There are many reasons why the service doesn't support a working environment, for example, the ONTAP version on your working environment could be below the required version. When you hover over an unsupported working environment, a tooltip displays the reason. 

You can download the results of the discovery process after discovery or from the Reports tab. 

For details, refer to link:rp-start-discover.html[Discover workloads in BlueXP ransomware protection]. 

//For details, refer to https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discovery.html[Discover workloads in BlueXP ransomware protection]. 