=== Landing page updates 
This release includes updates to the landing page for BlueXP ransomware protection that makes starting the free trial and discovery easier. 

=== Readiness drill updates 
Previously, you could run a ransomware readiness drill by simulating an attack on a new sample workload. With this feature, you can investigate the simulated attack and recover the workload. Use this feature to test alert notifications, response, and recovery. Run and schedule these drills as often as needed. 

With this release, you can use a new button on the BlueXP ransomware protection Dashboard to run a ransomware readiness drill on a test workload, making it easier for you to simulate ransomware attacks, investigate their impact, and recover workloads efficiently, all within a controlled environment.

You can now run readiness drills on CIFS (SMB) workloads in addition to NFS workloads. 

//For details, refer to link:rp-start-simulate.html[Conduct a ransomware attack readiness drill]. 

For details, refer to https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html[Conduct a ransomware attack readiness drill]. 

=== Enable BlueXP classification updates 

Before you use BlueXP classification within the BlueXP ransomware protection service, you need to enable BlueXP classification to scan your data. Classifying data helps you find personally identifiable information (PII), which can increase security risks. 

You can deploy BlueXP classification on a file share workload from within BlueXP ransomware protection. In the *Privacy exposure* column, select the *Identify exposure* option. If you've enabled the classification service, this action identifies the exposure. Otherwise, with this release, a dialog box presents the option to deploy BlueXP classification. Select *Deploy* to go to the BlueXP classification service landing page, where you can deploy that service. W

//For details, refer to https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html[Deploy BlueXP classification in the cloud^] and to use the service within BlueXP ransomware protection, refer to link:rp-use-protect-classify.html[Scan for personally identifiable information with BlueXP classification^]. 

For details, refer to https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html[Deploy BlueXP classification in the cloud^] and to use the service within BlueXP ransomware protection, refer to https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html[Scan for personally identifiable information with BlueXP classification].