=== Clean restore (public preview)

Ransomware Resilience now supports a clean restore option. 


=== ONTAP secondary 

Ransomware Resilience now supports replicating snapshots to ONTAP. 

For more information, see link:rp-use-protect.html[Protect workloads].
//For more information, see link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html[Protect workloads in Ransomware Resilience^].

=== Exclude workloads

If you don't want to include a workload in a system in the Ransomware Resilience dashboard, you can now exclude it. You can exclude workloads after discovery, and re-include them if you want to add ransomware protection. You aren't billed for exlcuded workloads. 

For more information, see link:rp-start-discover.html#exclude-workloads[Exclude workloads].
//For more information, see link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-discover.html#exclude-workloads[Exclude workloads^].

=== Unsupported volumes

Ransomware Resilience reports now capture information about supported and unsupported volumes in the **Summary** report. Use this information to diagnose why volumes in a system might be ineligible for ransomware protection. 

For more information, see link:rp-use-reports.html[Download reports].
// //For more information, see link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html[Download reports in Ransomware Resilience^].

=== Mark alerts as in review

Ransomware Resilience now allows you to mark alerts as "In review." With this settings, you can improve clarity across your team when triaging and managing active ransomware threats. 

For more information, see xref:rp-use-alert.html[Manage alerts].
//For more information, see link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html[Manage alerts in Ransomware Resilience^].