
=== Clean restore enhancements 

Clean restore now supports recovery to alternate clusters and analysis beyond seven days. 

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore.html[Recover workloads with a clean restore^].

=== Google SecOps SIEM support

Ransomware Resilience now supports security information and event management (SIEM) with Google SecOps, enabling you to send data automatically to Google SecOps for streamlined threat analysis and detection. 

For configuration information, see link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html[Connect Ransomware Resilience to a SIEM^].

=== Azure NetApp Files support is now generally available

Ransomware Resilience now supports Azure NetApp Files systems, enabling you to efficiently detect and respond to ransomware threats in Azure NetApp Files. When you discover workloads, Ransomware Resilience now presents Azure NetApp Files and displays them in the protection dashboard. Ransomware Resilience support for Azure NetApp Files includes detection and protection strategies with snapshots only. Support for Azure NetApp Files is now generally available (GA).

For more information, see link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html[Learn about Ransomware Resilience^].

=== SOAR support for blocking users 

Ransomware Resilience now supports blocking individual users with Google SecOps and Splunk SOAR playbooks. With this addition, you can automate blocking users when Ransomware Resilience detects suspicious user activity such as a data breach or mass deletion of data. 

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html[Integrate a SOAR playbook^].