=== Google Cloud NetApp Volumes support (preview)

Ransomware Resilience now supports Google Cloud NetApp Volumes systems, enabling you to efficiently detect and respond to ransomware threats in Google Cloud NetApp Volumes. When you conduct discovery, Ransomware Resilience automatically displays workloads from Google Cloud NetApp Volumes systems. When you discover the systems, they appear in the Ransomware Resilience dashboard. Support for Google Cloud NetApp Volumes in Ransomware Resilience is currently in preview. 

For more information, see link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html[Learn about Ransomware Resilience^]. For information about the scope of Google Cloud NetApp Volumes support, review link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html[Limitations in Ransomware Resilience^].

=== Clean restore enhancements

Clean restore now supports reports. With reports, you can review and assess clean restores, saving this information offline as a CSV file. 

Clean restore also now support stopping the analysis. If you stop the analysis, you must begin the clean restore again. 

To learn more about reports, see link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html[Download reports in Ransomware Resilience^]. To learn more about recovery, see link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html[Recover workloads with a clean restore^].
